name: Build on PR

on:
  pull_request_target:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.base_ref }}

jobs:
  run:
    name: Build on PR
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go get ./nanoid

      - uses: golangci/golangci-lint-action@v5
        with:
          version: latest

      - run: go test ./...
      - run: go build ./nanoid
